#!/usr/bin/env python3
"""Generate trap-stubs for every kernel/xam import referenced by the recompiled ppc/ code,
so the recompiled image can LINK before the real runtime exists (TASK 4, "link with stubs").

Each stub: PPC_FUNC_IMPL(__imp__<name>) { warn once; trap; }  — replace with a real impl,
behaviour reference: ../../third_party/rexglue-sdk/src/ (implements these for this exact title).

Run from anywhere; writes import_stubs.gen.cpp next to this script."""
import re, glob, os
HERE = os.path.dirname(os.path.abspath(__file__))
PPC = os.path.join(HERE, '..', 'ppc')
names = set()
for fn in glob.glob(os.path.join(PPC, '*.cpp')) + glob.glob(os.path.join(PPC, '*.h')):
    with open(fn) as f:
        for m in re.findall(r'__imp__([A-Za-z0-9_]+)', f.read()):
            if not m.startswith('sub_'):
                names.add(m)
names = sorted(names)
out = os.path.join(HERE, 'import_stubs.gen.cpp')
with open(out, 'w') as f:
    f.write('// AUTO-GENERATED by gen_import_stubs.py — DO NOT EDIT.\n')
    f.write('// Trap-stubs for kernel/xam imports so the recompiled image links.\n')
    f.write('// Replace each with a real implementation; behaviour reference:\n')
    f.write('//   ../../third_party/rexglue-sdk/src/  (this exact title) + Xenia / UnleashedRecomp.\n')
    f.write('#include "ppc_recomp_shared.h"\n#include <cstdio>\n\n')
    for n in names:
        # Imports are declared C++-linkage in ppc_recomp_shared.h via PPC_EXTERN_FUNC, so define
        # with plain PPC_FUNC (NOT PPC_FUNC_IMPL, which is extern "C") to match the symbol linkage.
        # WEAK so a real implementation in kernel.cpp (strong symbol) overrides the trap-stub.
        f.write(f'__attribute__((weak)) PPC_FUNC(__imp__{n}) {{ static bool w=false; if(!w){{w=true; fprintf(stderr,"[unimpl import] {n}\\n");}} __builtin_trap(); }}\n')
    f.write(f'\n// {len(names)} kernel/xam import stubs\n')
print(f"wrote {out}: {len(names)} stubs")
